// TypeScript test file parser.
// Port of Rust implementation from oxc/tasks/coverage/src/typescript/meta.rs
// Generated by GitHub Copilot initially and amended since.
//
// This file is duplicated in `oxc-project/oxc` repo in `napi/parser/test` directory.
// Any changes made here also need to be replicated there.

import fs from "node:fs";
import path from "node:path";

// Regex patterns equivalent to the Rust version
const META_OPTIONS_REGEX = /^\/\/\s*@(\w+)\s*:\s*([^\r\n]*)/gm;

/**
 * Convert settings value to boolean
 * @param value - Setting value
 * @param defaultValue - Default value if setting is not present
 * @returns Converted boolean value
 */
function valueToBoolean(value: string | undefined, defaultValue: boolean): boolean {
  if (value === "true") return true;
  if (value === "false") return false;
  return defaultValue;
}

/**
 * Split comma-separated values into array
 * @param value - Setting value
 */
function splitValueOptions(value: string | undefined): string[] {
  if (!value) return [];
  return value.split(",").map((s) => s.trim().toLowerCase());
}

/**
 * Create compiler settings from options map
 * @param options - Compiler options
 * @returns Compiler settings
 */
function createCompilerSettings(options: Map<string, string>): CompilerSettings {
  return {
    modules: splitValueOptions(options.get("module")),
    targets: splitValueOptions(options.get("target")),
    strict: valueToBoolean(options.get("strict"), false),
    jsx: splitValueOptions(options.get("jsx")),
    declaration: valueToBoolean(options.get("declaration"), false),
    emitDeclarationOnly: valueToBoolean(options.get("emitdeclarationonly"), false),
    alwaysStrict: valueToBoolean(options.get("alwaysstrict"), false),
    allowUnreachableCode: valueToBoolean(options.get("allowunreachablecode"), true),
    allowUnusedLabels: valueToBoolean(options.get("allowunusedlabels"), true),
    noFallthroughCasesInSwitch: valueToBoolean(options.get("nofallthroughcasesinswitch"), false),
    moduleDetection: splitValueOptions(options.get("moduledetection")), // "auto", "legacy", "force"
  };
}

// Mapping from file extension to source type
const EXTENSIONS: Record<string, SourceType> = {
  ".js": { typescript: false, jsx: false, module: true },
  ".mjs": { typescript: false, jsx: false, module: true },
  ".cjs": { typescript: false, jsx: false, module: false },
  ".jsx": { typescript: false, jsx: true, module: true },
  ".ts": { typescript: true, jsx: false, module: true },
  ".mts": { typescript: true, jsx: false, module: true },
  ".cts": { typescript: true, jsx: false, module: false },
  ".tsx": { typescript: true, jsx: true, module: true },
};

/**
 * Returns the effective moduleDetection mode based on settings.
 * - If explicitly set to non-"auto", returns that value
 * - For jsx/tsx files with react-jsx setting, returns "force"
 * - Default: "legacy"
 * @param settings - Compiler settings
 * @param filename - File name
 * @returns Effective module detection mode
 */
function getModuleDetectionMode(settings: CompilerSettings, filename: string): string {
  const mode = settings.moduleDetection[0] ?? "auto";
  if (mode !== "auto") {
    return mode;
  }
  const ext = path.extname(filename).toLowerCase();
  if ((ext === ".jsx" || ext === ".tsx") && settings.jsx[0] === "react-jsx") {
    return "force";
  }
  // NOTE: should check `package.json` "type" field, use `legacy` for now
  return "legacy";
}

/**
 * Check if file is a declaration file
 * @param name - File name
 * @returns Whether the file is a declaration file
 */
function isDeclarationFile(name: string): boolean {
  return name.endsWith(".d.ts") || name.endsWith(".d.mts") || name.endsWith(".d.cts");
}

/**
 * Check if extension explicitly indicates module type
 * @param ext - File extension (lowercase, with dot)
 * @returns Whether the extension has explicit module semantics
 */
function isExplicitModuleExtension(ext: string): boolean {
  return [".mts", ".mjs", ".cjs", ".cts"].includes(ext);
}

/**
 * Get source type from file path
 * @param filePath - Path to the file
 * @param options - Compiler options
 * @returns Source type, if supported
 */
function getSourceType(filePath: string, options: CompilerSettings): SourceType | null {
  const ext = path.extname(filePath).toLowerCase();
  let sourceType = EXTENSIONS[ext];

  if (!sourceType) return null;

  // For explicit module extensions (.mts, .mjs, .cjs, .cts), preserve the extension-based module value.
  // For ambiguous extensions (.js, .jsx, .ts, .tsx), use content-based detection (start with false).
  sourceType = {
    ...sourceType,
    module: isExplicitModuleExtension(ext) ? sourceType.module : false,
  };
  if (options.jsx.length > 0) sourceType.jsx = true;

  return sourceType;
}

/**
 * Get error files for the test
 * @param filePath - Path to the test file
 * @param options - Compiler options
 * @returns Error file contents
 */
function getErrorFiles(filePath: string, options: CompilerSettings): string[] {
  const fileName = path.basename(filePath, path.extname(filePath));
  const root = path.join(process.cwd(), "typescript/tests/baselines/reference");

  const suffixes = [
    "",
    ...options.modules.map((module) => `(module=${module})`),
    ...options.targets.map((target) => `(target=${target})`),
    ...options.jsx.map((jsx) => `(jsx=${jsx})`),
  ];

  const errorFiles = [];

  for (const suffix of suffixes) {
    const errorPath = path.join(root, `${fileName}${suffix}.errors.txt`);
    try {
      if (fs.existsSync(errorPath)) {
        const errorFile = fs.readFileSync(errorPath, "utf8");
        errorFiles.push(errorFile);
      }
    } catch {
      // Skip if file doesn't exist or can't be read
    }
  }

  return errorFiles;
}

/**
 * Extract individual test units from a TypeScript test file
 * @param filePath - Path to the test file
 * @param code - Content of the test file
 * @returns TestCaseContent object
 */
export function makeUnitsFromTest(filePath: string, code: string): TestCaseContent {
  const currentFileOptions = new Map<string, string>();
  let currentFileName: string | null = null;
  const testUnitData: PendingTestUnit[] = [];
  let currentFileContent = "";

  // Process the file line by line
  const lines = code.split(/\r?\n/);
  if (lines[lines.length - 1] === "") lines.length--;

  for (const line of lines) {
    // Reset regex state
    META_OPTIONS_REGEX.lastIndex = 0;
    const match = META_OPTIONS_REGEX.exec(line);

    if (match) {
      const metaName = match[1].toLowerCase();
      const metaValue = match[2].trim();

      if (metaName === "filename") {
        if (currentFileName !== null) {
          testUnitData.push({
            name: currentFileName,
            content: currentFileContent,
            sourceType: null, // Will be set later
          });
          currentFileContent = "";
        }
        currentFileName = metaValue;
      } else {
        currentFileOptions.set(metaName, metaValue);
      }
    } else {
      if (currentFileContent.length > 0) {
        currentFileContent += "\n";
      }
      currentFileContent += line;
    }
  }

  // Handle the last file (or the only file if no @filename is used)
  const fileName = currentFileName || path.basename(filePath);
  testUnitData.push({
    name: fileName,
    content: currentFileContent,
    sourceType: null, // Will be set later
  });

  const settings = createCompilerSettings(currentFileOptions);

  // Update source types and filter out unsupported files
  const validTestUnits: TestUnit[] = [];
  for (const unit of testUnitData) {
    const sourceType = getSourceType(unit.name, settings);
    if (!sourceType) continue;
    if (getModuleDetectionMode(settings, unit.name) === "force" && !isDeclarationFile(unit.name)) {
      sourceType.module = true;
    }
    validTestUnits.push({ ...unit, sourceType });
  }

  const errorFiles = getErrorFiles(filePath, settings);

  return {
    tests: validTestUnits,
    settings,
    errorFiles,
  };
}

interface CompilerSettings {
  modules: string[];
  targets: string[];
  strict: boolean;
  jsx: string[];
  declaration: boolean;
  emitDeclarationOnly: boolean;
  alwaysStrict: boolean;
  allowUnreachableCode: boolean;
  allowUnusedLabels: boolean;
  noFallthroughCasesInSwitch: boolean;
  moduleDetection: string[];
}

interface SourceType {
  typescript: boolean;
  jsx: boolean;
  module: boolean;
}

interface PendingTestUnit {
  name: string;
  content: string;
  sourceType: null;
}

export interface TestUnit extends Omit<PendingTestUnit, "sourceType"> {
  sourceType: SourceType;
}

export interface TestCaseContent {
  tests: TestUnit[];
  settings: CompilerSettings;
  errorFiles: string[];
}
